feat(release): add new behavior for relaese

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,45 @@
-name: Release 
+name: Release
+
+on:
+  workflow_call:
+
+jobs:
+  release:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Pull latest version tag
+        run: |
+          git fetch
+          git pull
+          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+          echo "LATEST_VERSION=${LATEST_TAG:1}" >> $GITHUB_ENV
+      - name: Retrieve build items
+        uses: actions/cache@v3
+        id: build-dotnet-cache
+        with:
+          path: ./**/Release/*.nupkg
+          key: build-dotnet-cache-${{ github.sha }}
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: ${{ env.LATEST_TAG }}
+          name: ${{ env.LATEST_VERSION }}
+          token: ${{ secrets.BOT_PAT }}
+          generate_release_notes: true
+          files: |
+            **/Release/*.nupkg
+
+
+
+##########
+#name: Release 
 # The new release workflow is triggered when a new tag on the release
 # branch is pushed.
 #
@@ -24,64 +65,65 @@ name: Release
 #      - Upload the vsix file as an asset of the release
 #      - For stable version release (vX.X.X), upload to the vscode market place
 #        (not implemented in this CL)
-on:
-  push:
-    tags: [ "*" ]
-jobs:
-  build:
-    name: create release
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout code
-        uses: actions/checkout@v2
-      - name: get release version
-        id: release_version
-        run: |
-          TAGGED_VERSION="${GITHUB_REF/refs\/tags\/v/}"
-          if [[ ! "${TAGGED_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
-            echo "Invalid version tag '${TAGGED_VERSION}'"
-            exit 1
-          fi
-          echo ::set-env name=EXT_VERSION::"${TAGGED_VERSION}"
-          WRITTEN_VERSION="$(cat package.json | jq '.version' -r)"
-          if [[ ${TAGGED_VERSION} == *"-"* ]]; then
-            echo ::set-env name=EXT_ISPREVIEW::1
-          else
-            if [[ "${TAGGED_VERSION}" != "${WRITTEN_VERSION}" ]]; then
-              echo "Release Tag and Version in package.json do not match: '${TAGGED_VERSION}' vs '${WRITTEN_VERSION}'"
-              exit 1
-            fi
-            echo ::set-env name=EXT_ISPREVIEW::0
-          fi
-      - name: stamp version
-        run: |
-          cat package.json | jq --arg VER "${{ env.EXT_VERSION }}" '.version=$VER' > /tmp/package.json 
-          cp /tmp/package.json ./package.json
-          npm ci
-          npm run vscode:prepublish
-      - name: package
-        uses: lannonbr/vsce-action@704da577da0f27de5cdb4ae018374c2f08b5f523
-        with:
-          args: "package"
-      - name: create release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ env.EXT_VERSION }}
-          draft: false
-          prerelease: ${{env.EXT_ISPREVIEW == 1}}
-      - name: upload release asset
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./go-${{ env.EXT_VERSION }}.vsix
-          asset_name: go-${{ env.EXT_VERSION }}.vsix
-          asset_content_type: application/zip
+#on:
+#  push:
+#    tags: [ "*" ]
+#jobs:
+#  build:
+#    name: create release
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: checkout code
+#        uses: actions/checkout@v2
+#      - name: get release version
+#       id: release_version
+#       run: |
+#         TAGGED_VERSION="${GITHUB_REF/refs\/tags\/v/}"
+#         if [[ ! "${TAGGED_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
+#           echo "Invalid version tag '${TAGGED_VERSION}'"
+#           exit 1
+#         fi
+#         echo ::set-env name=EXT_VERSION::"${TAGGED_VERSION}"
+#         WRITTEN_VERSION="$(cat package.json | jq '.version' -r)"
+#         if [[ ${TAGGED_VERSION} == *"-"* ]]; then
+#           echo ::set-env name=EXT_ISPREVIEW::1
+#          else
+#            if [[ "${TAGGED_VERSION}" != "${WRITTEN_VERSION}" ]]; then
+#              echo "Release Tag and Version in package.json do not match: '${TAGGED_VERSION}' vs '${WRITTEN_VERSION}'"
+#              exit 1
+#            fi
+#            echo ::set-env name=EXT_ISPREVIEW::0
+#          fi
+#      - name: stamp version
+#        run: |
+#          cat package.json | jq --arg VER "${{ env.EXT_VERSION }}" '.version=$VER' > /tmp/package.json 
+#          cp /tmp/package.json ./package.json
+#          npm ci
+#          npm run vscode:prepublish
+#      - name: package
+#        uses: lannonbr/vsce-action@704da577da0f27de5cdb4ae018374c2f08b5f523
+#        with:
+#          args: "package"
+#      - name: create release
+#        id: create_release
+#        uses: actions/create-release@v1
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        with:
+#          tag_name: ${{ github.ref }}
+#          release_name: Release ${{ env.EXT_VERSION }}
+#          draft: false
+#          prerelease: ${{env.EXT_ISPREVIEW == 1}}
+#      - name: upload release asset
+#        uses: actions/upload-release-asset@v1
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        with:
+#          upload_url: ${{ steps.create_release.outputs.upload_url }}
+#          asset_path: ./go-${{ env.EXT_VERSION }}.vsix
+#          asset_name: go-${{ env.EXT_VERSION }}.vsix
+#          asset_content_type: application/zip
 # TODO: check if the commit is in green state. (test-long.yml results)
 # TODO: publish to the market if VERSION is for a stable version.
 # TODO: after publishing, create a gerrit CL to update 'latest' branch if VERSION is for a stable version.
+##########
